### ISSUE TITLE
migration from v4 to v5

### ISSUE THREAD

**Issue by TakamiChie** [agebrock/tunnel-ssh#100]
I wrote the following program in Tunnel-SSH v4:
```js
tunnel({
  host: host, port: port,
  username: username, password: password, 
  localHost: localHost, localPort: localPort,
  dstHost: dstHost, dstPort: dstPort,
  keepAlive: true,
}, (error, serv) => {
  if(error){
    // What to do when a connection fails
  }else{
    // What to do when a connection is successful
  }
});
```

```mermaid
flowchart LR
    A["localHost"] -->|Tunneling| B["host"]
    B -->|Tunneling| C["dstHost"]
```

The API has changed significantly in v5, but it is not known which parameter corresponds to which value of the previous version, and it cannot be migrated.
Where can I find information about migration?

**Comment by agebrock** [comment]
Hi @TakamiChie 

The configuration is almost the same , just grouped a bit different. 

- dstHost, dstPort goes to the =>  forwarding options. (in your case srcAddr and srcPort are most likely the same)
- host, port, username, password are ssh server related +> sshoptions. 
- and localHost and localPort  is where your localTCP Server is listening => serverOptions. 
- keepAlive => tunnelOptions (autoClose:false)

Please let me know if that helps . We will update the Readme soon.

**Comment by TakamiChie** [comment]
Thanks for the reply.
I wrote the following program in accordance with your point.

```js
const { createTunnel } = require('tunnel-ssh');

const tunnelOptions = {
  autoClose:false
};
const serverOptions = {
  host: localHost, port: localPort
};
const sshOptions = {
  host: host, port: port,
  username: username, password: password,
}
const forwardOptions = {
  srcAddr:host, srcPort:port,
  dstAddr:dstHost, dstPort:dstPort
}
let [[serv, conn], error] = await createTunnel(tunnelOptions, serverOptions, sshOptions, forwardOptions);
```
However, the following error is displayed when the `createTunnel()` method is executed.
```
(node:9252) UnhandledPromiseRejectionWarning: Error: listen EADDRINUSE: address already in use [localHost]:[localPort]
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at doListen (node:net:1559:7)
    at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```
Am I misunderstanding your point?

**Comment by agebrock** [comment]
actually your config looks right.  The error indicates that something on the port : localPort is already listening. 
As a hint how to find out what is listening you can check the following site maybe it will help you : 
https://stackoverflow.com/questions/4075287/node-express-eaddrinuse-address-already-in-use-kill-server

FYI in the 5.0.5 version that error is catchable, this will not solve your issue you can just handle it different.

**Comment by TakamiChie** [comment]
Sorry for the late contact.

When the code was simplified as much as possible and the process was executed, the server and client objects were obtained as intended.

We look forward to continuing to update the Readme.
