### ISSUE TITLE
Server is not closed if client fails

### ISSUE THREAD

**Issue by lenchvolodymyr** [agebrock/tunnel-ssh#101]
If server is created successfully, but then client fails (e.g. ECONNRESET when port is wrong), the server is not closed, and port remain busy until you kill the entire process. It would be good to close the server, or pass it within the error.

```       
try {
            server = await createServer(serverOptions);
        } catch (e) {
            return reject(e);
        }
```
```
        try {
            conn = await createClient(sshOptions);
        } catch (e) {
            return reject(e);
        }
```

**Comment by gpetrov** [comment]
Got this as well, happens for example when authentication fails.
On retry the error pops up that port is already in use because server is still running...

@agebrock can you make sure the server is just closed on errors?

**Comment by nitzan-blink** [comment]
@agebrock having this problem too. 
@gpetrov code seems to work fine to handle the server errors.
any plans to merge?
