### ISSUE TITLE
There is no way to specify dynamic port

### ISSUE THREAD

**Issue by lenchvolodymyr** [agebrock/tunnel-ssh#102]
There is a possibility to let the OS assign the free port dynamically if set 0 value:
[server.listen()](https://nodejs.org/api/net.html#serverlistenport-host-backlog-callback)

```
If port is omitted or is 0, the operating system will assign an arbitrary unused port, which can be retrieved by using server.address().port after the ['listening'](https://nodejs.org/api/net.html#event-listening) event has been emitted.
```

It would be great if `srcPort` in forwardOptions was taken from `server.address().port` 

Currently, there is no way to get port dynamically, because we have to specify srcPort explicitely.

**Comment by agebrock** [comment]
I will have a look into that on the weekend that should be doable.

**Comment by agebrock** [comment]
@lenchvolodymyr  thanks for that request. I added support for dynamic port assignment in the 5.0.8 version. 
Let me know if that suites your needs.
