### ISSUE TITLE
Add typescript support / update @types/tunnel-ssh

### ISSUE THREAD

**Issue by amal-chandran** [agebrock/tunnel-ssh#104]
- While using typescript its difficult to use the lib without types
- Currently, the types lib are falling behind it only had updates till 4.1.1

**Comment by agebrock** [comment]
This may take a while since I am not into Typescript and this is a little out of scope for me. 
I will have a look into it. But I can not give you an estimation on this issue. sorry for that

**Comment by derekrliang** [comment]
If this helps, this is my local types file to get it working.

`types.d`
```
import { Server } from 'net';
import { Client, ConnectConfig } from 'ssh2';

declare module 'tunnel-ssh' {
  interface TunnelOptions {
    autoClose: boolean;
  }

  declare function createTunnel(
    tunnelOptions: TunnelOptions,
    serverOptions,
    sshOptions: ConnectConfig,
    forwardOptions,
  ): Promise<[Server, Client]>;
}

```

**Comment by agebrock** [comment]
Ok that is already a good start. I will have a look. Thank you

**Comment by agebrock** [comment]
Awesome , 
Thank you I added your file to 5.0.7. 

Feel free to provide a pull request to improve support.

**Comment by ryubal-sh** [comment]
Just as a heads up, this fails with the latest version.
<img width="890" alt="Screenshot 2023-06-23 at 10 33 01 a m" src="https://github.com/agebrock/tunnel-ssh/assets/102773109/d7d6e6e7-5403-4f6f-bea2-635fac8de6e0">

Installing an older version and types manually works:
```
npm i tunnel-ssh@5.0.5
npm i @types/tunnel-ssh
```
