### ISSUE TITLE
About tunneling with Redis cluster (AWS Memory DB)

### ISSUE THREAD

**Issue by Gimmingyu** [agebrock/tunnel-ssh#114]
I'm trying to connect with my AWS Memory DB.

This is my function for SSH tunneling.

```typescript 
export async function useSSHTunnel(
  host: string,
  destPort: number,
  localPort?: number,
) {
  const path = `${__dirname}/../../${process.env.PEM}`;
  const key = fs.readFileSync(path);

  const tunnelOptions: TunnelOptions = {
    autoClose: true,
  };

  const serverOptions: ServerOptions = {
    host: '127.0.0.1',
    port: localPort,
  };

  const forwardOptions: ForwardOptions = {
    dstAddr: host,
    dstPort: destPort,
    srcPort: localPort,
    srcAddr: '0.0.0.0',
  };

  const sshOptions: SshOptions = {
    host: process.env.SSH_HOST as string,
    port: 22,
    privateKey: key,
    username: process.env.SSH_USERNAME as string,
    agent: process.env.SSH_AUTH_SOCK as string,
  };

  await createTunnel(
    tunnelOptions,
    serverOptions,
    sshOptions,
    forwardOptions,
  ).then(([server, conn]) => {
    server
      .on('connection', (...args) => {
        console.log('connection!!');
        return;
      })
      .on('error', (err) => {
        console.log('error!!');
        console.log(err);
        return;
      })
      .on('close', () => {
        console.log('close!!');
        return;
      })
      .on('listening', () => {
        console.log('listening!!');
        return;
      });

    conn.on('error', (err: any) => {
      console.error(err);
      return;
    });
  });
}
```

I've already accessed to my AWS RDS, so I think the code is not the cause.

I call the function like this. 

```typescript
await useSSHTunnel(
    process.env.REDIS_TUNNELING_HOST as string,
    config.REDIS_PORT,
    dynamicPort(),
  );

await useSSHTunnel(
    process.env.REDIS_NODE_HOST1 as string,
    Number(config.REDIS_PORT),
    dynamicPort(),
  );
  await useSSHTunnel(
    process.env.REDIS_NODE_HOST2 as string,
    Number(config.REDIS_PORT),
    dynamicPort(),
  );
```

But it doesn't work properly, while I tried to connect to a RDS with a specific port (in my case 3306), it will work correctly and print output.

I don't know what the problem is. I'd appreciate help.

**Comment by dyaacov** [comment]
How did you access the DB?
I'm able to open  the tunnel but not accessing the DB

`

async function main () {

onst tunnelOptions = {
    autoClose:true
};
const serverOptions = {
    port: port
};
const sshOptions = {
    host: 'xx.xx.xx', // AWS EC2 for ssh tunneling
    port: 22,
    username: 'ubuntu',
    privateKey:fs.readFileSync(`/***.cer`),
    agent:process.env.SSH_AUTH_SOCK
};
const forwardOptions = {
  dstAddr: '127.0.0.1',
  dstPort: port
};


    console.log('creating tunnel...');
    try {
        let [server, conn] = await createTunnel(tunnelOptions, serverOptions, sshOptions, forwardOptions);
        console.log('tunnel created');

        connect(uri, {
            useNewUrlParser: true,
            useFindAndModify: false,
            useUnifiedTopology: true,
            sslValidate: true,
            sslCA: ca, // **this is the rds-combined-ca-bundle.pem**
            }).then(() => console.info(`Successfully connected to ${uri}`)).catch(e => console.log(e));


`
