### ISSUE TITLE
"passphrase" instead of "password" in RSA Example config

### ISSUE THREAD

**Issue by kepikoi** [agebrock/tunnel-ssh#48]
when using an encrypted private key following Error is thrown when using the example config from readme
` throw new Error('Encrypted private key detected, but no passphrase given'); `

The readme suggests using "password" in the config, though "passphrase" is the correct key.

**Comment by agebrock** [comment]
Hi @kepikoi, thank you for reporting your issue. 
Both options or keys are possible, usually you use "password only" to authenticate or your private key with an optional passphrase. 
 
Please have a look at [client-methods of the ssh2 readme](https://github.com/mscdex/ssh2#client-methods) for more information. 

I will add the missing information in the future readme. 

Thanks for sharing your problem
