### ISSUE TITLE
problems with mongodump

### ISSUE THREAD

**Issue by adrai** [agebrock/tunnel-ssh#51]
I'm not able to dump through a tunnel to a mongodb server...

This works:
`ssh -L 27018:localhost:27017 localhost -N`
`mongodump --port=27018`

This not:
```
const tunnel = require('tunnel-ssh');
const config = {
  username: 'usr',
  password: 'pwd',
  host: 'localhost',
  port: 22,
  dstHost: 'localhost',
  dstPort: 27017,
  localPort: 27016
};
tunnel(config, (err, tnl) => {
  console.log(err);
});
```
`mongodump --port=27016`

My actual more real use case works not on localhost but something like this:
equivalent ssh command for tunnel: `ssh -L 44041:remotemongoserver:44147 user@remotesshserver -p 2222 -N`
mongodump command: `mongodump --host=localhost --port=44041 --username=dbuser --password=dbpassword --db=mydb --out=/Users/adrai/Projects/my-backuper/backups && mv /Users/adrai/Projects/my-backuper/backups/mydb /Users/adrai/Projects/my-backuper/backups/app-readmodel`
And this works like you expect with ssh cli.

Do I miss something?

**Comment by adrai** [comment]
@mscdex any idea?

**Comment by agebrock** [comment]
Hi, i can not reproduce your problem, works great here. 
Can you provide an error message ? 

Please note that the tunnel will automatically close after all connections are closed. 
For example if you connect to the mongoshell and terminate the connection or do a dump. 

If thats your problem then you should set "keepAlive:true"

```
const config = {
  keepAlive:true,
  host: 'localhost',
  dstPort: 27017,
  localPort: 27016
};
tunnel(config, (err, tnl) => {
  console.log(err);
});

```

**Comment by adrai** [comment]
keepAlive seems not to work...

this is the node output:
```
  tunnel-ssh sshConnection:ready +9s
  tunnel-ssh sshStream:create +26ms
{ Error: All configured authentication methods failed
    at tryNextAuth (/Users/adrai/Projects/taibika-backuper/node_modules/ssh2/lib/client.js:376:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/Users/adrai/Projects/taibika-backuper/node_modules/ssh2/lib/client.js:587:5)
    at emitTwo (events.js:125:13)
    at SSH2Stream.emit (events.js:213:7)
    at parsePacket (/Users/adrai/Projects/taibika-backuper/node_modules/ssh2-streams/lib/ssh.js:3928:10)
    at SSH2Stream._transform (/Users/adrai/Projects/taibika-backuper/node_modules/ssh2-streams/lib/ssh.js:668:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/Users/adrai/Projects/taibika-backuper/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:371:12) level: 'client-authentication' }
{ Error: All configured authentication methods failed
    at tryNextAuth (/Users/adrai/Projects/taibika-backuper/node_modules/ssh2/lib/client.js:376:17)
    at SSH2Stream.onUSERAUTH_FAILURE (/Users/adrai/Projects/taibika-backuper/node_modules/ssh2/lib/client.js:587:5)
    at emitTwo (events.js:125:13)
    at SSH2Stream.emit (events.js:213:7)
    at parsePacket (/Users/adrai/Projects/taibika-backuper/node_modules/ssh2-streams/lib/ssh.js:3928:10)
    at SSH2Stream._transform (/Users/adrai/Projects/taibika-backuper/node_modules/ssh2-streams/lib/ssh.js:668:13)
    at SSH2Stream.Transform._read (_stream_transform.js:190:10)
    at SSH2Stream._read (/Users/adrai/Projects/taibika-backuper/node_modules/ssh2-streams/lib/ssh.js:251:15)
    at SSH2Stream.Transform._write (_stream_transform.js:178:12)
    at doWrite (_stream_writable.js:371:12) level: 'client-authentication' }
```


`mongodump --host=localhost --port=48274 --username=usr --password=secret --db=mydb --out=/Users/adrai/Projects/my-backuper/backups && mv /Users/adrai/Projects/my/backups/mydb /Users/adrai/Projects/my-backuper/backups/my-app-readmodel -v`

and this the command output:
`2017-06-28T09:39:26.036+0200	Failed: error counting mydb.tablename: Closed explicitly`

**Comment by adrai** [comment]
if I try with the mongo cli it works:

```
mongo --host=localhost --port=49108 --username=usr --password=secret mydb
MongoDB shell version v3.4.4
connecting to: mongodb://localhost:49108/mydb
MongoDB server version: 3.2.9
WARNING: shell and server versions do not match
> show collections
tablename
col1
col2
col3
>
```

**Comment by agebrock** [comment]
That error means that the tunnel was not able to log into localhost. 
You may try to use my code above since tunnel uses your current user and the ssh agent to simulate the same behaviour known from the ssh command, witch means if you don't need a password there you should not need one for tunnel-ssh.

**Comment by adrai** [comment]
but I need a password there

**Comment by agebrock** [comment]
ok in that case try to use the ssh command first to make sure everything works as expected. 

You may need a passphrase instead of a password ?

**Comment by adrai** [comment]
see my comment here: https://github.com/agebrock/tunnel-ssh/issues/51#issuecomment-311583781 the tunnel is open and works normally when using mongo client.
The only problem I have is when using the same tunnel with mongodump

**Comment by adrai** [comment]
Seems like mongodump is doing multiple requests... the first passes but the next requests not...

**Comment by adrai** [comment]
Same behaviour with a tunneled s3 service

**Comment by adrai** [comment]
What if my ssh password is a one-time-code that is invalid immediately after having used...
So the first TCP call (that triggers a ssh authentication) works and the second TCP call (that also triggers a ssh authentication) is not working anymore... because the password is not valid anymore for a new session...
https://github.com/mscdex/ssh2/blob/master/lib/client.js#L391
Any advice @mscdex how I can have an open ssh session without having each tcp call to create a new one (and authenticating again)?

**Comment by mscdex** [comment]
@adrai You can call `forwardOut()` as many times as the server allows you.

**Comment by agebrock** [comment]
@adrai can you please try the current development branch and tell me if that fixes your issue ...

**Comment by adrai** [comment]
first short test seems to get into timeout now... 

```
  tunnel-ssh sshConnection:ready +436ms
  tunnel-ssh sshStream:create +26ms
  tunnel-ssh netConnection::end +36s
```

**Comment by agebrock** [comment]
all right I will dig into that a little deeper it seems a quite interesting case.

**Comment by agebrock** [comment]
all right I will dig into that a little deeper it seems to be a quite interesting case.

**Comment by agebrock** [comment]
@adrai I fixed the timeout issue. Let me know if it finally covers your case.

**Comment by adrai** [comment]
works 👍

**Comment by agebrock** [comment]
Version 5 uses forward out all the time. mondodump should not be an issue anymore
