### ISSUE TITLE
ECONNRESET Error

### ISSUE THREAD

**Issue by staminna** [agebrock/tunnel-ssh#54]
Hi

I've applied code to a MEAN.JS stack app which goes like this:
```
var config = {
    username:'jorge',
    host:'127.0.0.1',
    agent : process.env.SSH_AUTH_SOCK,
    privateKey:require('fs').readFileSync('/Users/jorge/.ssh/id_rsa'),
    port:22,
    dstPort:27017,
	password:'xxxxxxxxx',
	passphrase:'yyyyyyyy'
};

var server = tunnel(config, function (error, server) {
    if(error){
        console.log("SSH connection error: " + error);
    }
    mongoose.connect('mongodb://localhost:27017/webapplication');

    var db = mongoose.connection;
    db.on('error', console.error.bind(console, 'DB connection error:'));
    db.once('open', function() {
        // we're connected!
        console.log("DB connection successful");
    });
		
	// Init the express application
	var app = require('./config/express')(db);
	
	// Start the app by listening on <port>
	app.listen(8443);
	
	// Expose app
	exports = module.exports = app;
});

``` 

> MEAN.JS application started on port 22

> Securely using https protocol

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:907:11)
    at TCP.onread (net.js:558:26)

**Comment by agebrock** [comment]
Hi there,

can you explain to me, what you want to do ? It looks like you are
connecting to yourself since you use localhost and do not map any ports.

**Comment by staminna** [comment]
I would like to connect to Mongodb using mongoose on localhost with ssh tunneling on localhost.

**Comment by agebrock** [comment]
I hope you managed to get it to work already. The problem you seem to have is that you are trying to bind a port that is already in use. I think the easiest way to solve your problem is just mapping the mongoDB port somehow different then 27017, this should work with your production system as well.
