### ISSUE TITLE
How to know that connection was established successfully?

### ISSUE THREAD

**Issue by bushev** [agebrock/tunnel-ssh#55]
Hello!

Right now I run this scenario:

1. Start connection with the wrong password
2. Callback called `error=null`
3. After some time (2 - 3 seconds) `error` event received

So, I need to start a timeout (it can be more than 3 seconds) to wait for a proper connection status.

My application wants to know a connection status (success/error) as soon as possible. What is the solution?

**Comment by agebrock** [comment]
Hi there, the error event does not bubble right now .. .to catch the error you need to access the underlaying sshConnection .. 

```
  var tnl = tunnel(config, (server, error)  => {});
  tnl.sshConnection.on('error',(e) => console.log(e.message));
```
I hope that does the trick for you.

**Comment by bushev** [comment]
So, status is WONTFIX?
