### ISSUE TITLE
Question: Equivalent plink command in js

### ISSUE THREAD

**Issue by aberbegall** [agebrock/tunnel-ssh#56]
Currently I am using these two modules

- **Websockify**; [webSocket to TCP proxy javascript for Node.js](https://github.com/novnc/websockify/blob/master/other/js/websockify.js)

- **plink.exe**; [SSH client with port redirect for windows](https://the.earth.li/~sgtatham/putty/0.70/htmldoc/Chapter7.html)

In order to open a web socket connection with a remote VNC server (port 5900). To achieve that currently I use plink to create a ssh tunnel to a remote VNC server and redirect the remote port 5900 over ssh tunnel.

This is the plink command I execute:
> plink.exe -L 3333:localhost:5900 -i key.ppk user@remotehost -pw passphrase

And I would like to integrate that **plink** functionality into the **websockify** script.

Would that be possible with **tunnel-ssh**?
Thanks in advance :)

**Comment by agebrock** [comment]
yes 👍 
```
  var config = {
      username:'user',
      passphrase:'passphrase',
      host: 'remotehost ',
      dstPort: 5900,
      localPort: 3333
    };

```

**Comment by aberbegall** [comment]
Thanks for the comment... I will check that next week I provide some feedback.

**Comment by aberbegall** [comment]
I only needed to add the key file to the config you posted. And it worked like a charm :)

 var config = {
        username: 'user',
        privateKey: fs.readFileSync("key.ppk"),
        passphrase: 'passphrase',
        host: 'remotehost',
        port:22,
        dstPort: 5900,
        localPort: 3333
      };  

Thanks again :)
