### ISSUE TITLE
How do you create an SSH tunnel from localhost to a particular server?

### ISSUE THREAD

**Issue by donpinkus** [agebrock/tunnel-ssh#61]
We have a few attributes available in the config that are not clearly diffentiated:
```
host
port
dstHost
dstPort
localHost
localPort
```

How do I connect my localhost (127.0.0.1) 
to a remote server (10.10.10.10, username: foo, password: bar) 
with a MySQL instance (mysql user: foo, mysql pass: bar, mysql db: my_db, mysql port: 2222)?

In command line, I can do: `ssh -L 2222:localhost:2222 foo@10.10.10.10`, and then enter my password. Then in NodeJS, I would just connect to MySQL on port 2222 since it is tunneled.

**Comment by antoniobusrod** [comment]
Hi @donpinkus , I think next configuration should work.

```
host: 10.10.10.10
port: 22
username: 'foo'
password: 'bar'
dstHost: 'localhost'
dstPort: 2222
localHost: 'localhost'
localPort: 2222
```
