### ISSUE TITLE
Error not captured inside the function callback

### ISSUE THREAD

**Issue by rajbrt** [agebrock/tunnel-ssh#64]
When passing the incorrect private key file, the error thrown("Error: All configured authentication methods failed") is not captured inside the function callback. But able to capture it as part of "error" event outside callback.

let tunnelsshConfig = {
  username: sshUserName,
  host: sshHostName,
  port: 22,
 dstHost: '127.0.0.1',
 dstPort: 27017,
 localHost: '127.0.0.1',
 localPort: xxxx8,
privateKey: privateKeyFile
}

tunnel(tunnelsshConfig, function(sshError, mongoServer) {
if (sshError) {
  console.log("sshError");
   console.log(error);
   dbConnectStatus = "false";
   callback(null);
     } else {              
console.log("Successful Connection");    
// Successful Code
}
});

**Comment by agebrock** [comment]
You can use the on('error') handler from the ssh-client in v5
