### ISSUE TITLE
Add a LICENSE file to this repository

### ISSUE THREAD

**Issue by aberbegall** [agebrock/tunnel-ssh#67]
Hello
I would like to ask you to please add the licence of your choice for tunnel-ssh.

As I can see in NPM states MIT (same as ssh):
[https://www.npmjs.com/package/tunnel-ssh](https://www.npmjs.com/package/tunnel-ssh)

but it's not clearly indicated in this repository.

Why is this important for us?
We need to ensure that we are able to use this tool and the lack of LICENCE can lead to legal confusion besides that we need the copyright notice included in the LICENCE.

Sorry to be picky with this request but is really important for us.
P.S: [adding-a-license-to-a-repository](https://help.github.com/articles/adding-a-license-to-a-repository/)

Thank you

**Comment by aberbegall** [comment]
https://github.com/agebrock/tunnel-ssh/pull/68

**Comment by aberbegall** [comment]
@agebrock would be great if you can merge this #68 
Thank you

**Comment by aberbegall** [comment]
Ping @agebrock

**Comment by agebrock** [comment]
Pong ! :) Working on it
