### ISSUE TITLE
Error: Cannot parse privateKey: Unsupported key format

### ISSUE THREAD

**Issue by sm-a** [agebrock/tunnel-ssh#72]
When I load the "privatekey" and establish a connection I get the following error message:
Error: Cannot parse privateKey: Unsupported key format

I load the "privatekey" as follows:
`privateKey: require('fs').readFileSync('/root/.ssh/id_rsa', { encoding: 'utf8' }).trim()`

The private key begins with:
-----BEGIN OPENSSH PRIVATE KEY-----

Is this a Bug or what I make false?

**Comment by agebrock** [comment]
You need a RSA key.  Just google for "convert openssh private key to rsa" you gonna find something for sure.
