### ISSUE TITLE
[feature-request] Keep Alive Timeout?

### ISSUE THREAD

**Issue by djMax** [agebrock/tunnel-ssh#76]
Right now keepAlive is "all or nothing" - what about if it's a number, that's the amount of time after the last closure to shut down the tunnel?

**Comment by agebrock** [comment]
Its all or nothing indeed. Version 5 checks every second if a remaining connection is open. 
Have a look into the implementation, you can disable the new autoclose function and implement your own.

**Comment by joneldiablo** [comment]
HI!! good day!! I having an issue here, I have set autoClose:false but the server close the connection, sooo  how can I set an option 


keepLive: true
|| ServerAliveInterval=120
|| ServerAliveCountMax=720 

??

this is my idea:
async function createTunnel(tunnelConfig, knexConfig) {
  const { tunnelOptions, serverOptions, sshOptions, forwardOptions } = tunnelConfig;
  const [server, conn] = await tunnel(tunnelOptions, serverOptions, sshOptions, forwardOptions);
  const port = server.address().port;
  knexConfig.connection.port = port;
  console.log('TUNNEL on port:', port);
  const db = await createKnex(knexConfig);
  if (db) {
    db._dbl_destroy = db.destroy;
    db.destroy = async function () {
      const toReturn = await db._dbl_destroy();
      await server.close(() => {
        console.log('tunnel & mysql conn CLOSE');
      });
      return toReturn;
    }
  }
  return db;
}
