### ISSUE TITLE
CLOSE_WAIT connections

### ISSUE THREAD

**Issue by ricardomat** [agebrock/tunnel-ssh#78]
When I try to establish concurrent connections through the same ssh tunnel using a tunnel-ssh module in low vpn speed access, after about 10 connections, I start to receive ECONNRESET error. This error leads to many CLOSE_WAIT tcp connections (netstat) that remain blocked forever. I ran this scenario using node versions 7, 8, 10 and 11.

The error happens in outbound connections (sshConnection). Once it take place, the outbound connection receives "close" event that does not reflect the inbound connection (netConnection), that remains active. Even if I try to close the tunnel (what is not desirable, since I may have healthy connections in it)  it does not emit close event, probably keeping this tunnel locked, since the server side still has established incoming connections. Checking server object is possible to verify that it has active connections (same amount in CLOSE_WAIT state).

The error that the application receives is related to the tunnel itself and does not distinguish any specific connection, so it is not possible to easily pinpoint and close the failed connections in application level. In this situation the event:
>>> netConnection.emit('sshConnection', sshConnection, netConnection); 

is not set, since sshConnection ready event never ocurred, because of the error. If this line is moved out of the "sshConnection.on ready" context, it will be possible to bind netConnection to sshConnection in this situation.

Another idea is to treat sshConnection close event, destroying netConnection associated to it. Note that by my tests netConnection.end() method is not enough to clear the connection reference in server object, only netConnection.destroy() makes it.

As a workaround I saved aside all connections received in "netConnection" event, until I receive ECONNRESET in the application. I timed out for a while to wait for tcp states to be changed, then checked /proc/net/tcp for CLOSE_WAIT connections. I compare them to the netConnections I was notified and force netConnection.destroy() to release it. Pretty ugly workaround, but it seems to be working for me.

I hope this can be helpfull to fix this problem

Thanks in advance

**Comment by agebrock** [comment]
I indeed had the same issue. I will observe if the issue still exists in the new version .
