### ISSUE TITLE
published npm version is out of date

### ISSUE THREAD

**Issue by tom-james-watson** [agebrock/tunnel-ssh#81]
The version published on npm is out of date with `master`. For example this fix is currently not available on the npm package - https://github.com/agebrock/tunnel-ssh/commit/76379ea786f5620353735f8343089c648507828d

Can you please publish a new version?

Thanks!

**Comment by RobeeeJay** [comment]
I think I need this commit too, but 4.1.5 isn't published to npm 😢

**Comment by tom-james-watson** [comment]
4.1.6 has been published to npm now.
