### ISSUE TITLE
Dsconnection takes too long

### ISSUE THREAD

**Issue by yomonah** [agebrock/tunnel-ssh#90]
I connect a ssh tunnel to remote serve, when I don't want to use it anymore, I‘d like to close it. Actually when I close it, I found it takes so long time to finish whole connection, at least 3 minutes or more. It's not friendly for users. I wonder it's something wrong with my codes or the disconnection itself takes so long? I'll be greatful if you can give me any advise, thanks.

**Comment by agebrock** [comment]
Hi that issue us most likely caused because tunnel-ssh creates a new ssh client for each connection. 
I changed the that in v5 please try again. If you still having issues like that please post your ssh version and the architecture your are using . 

Thanks
