### ISSUE TITLE
Supporting ed25519 ssh keys

### ISSUE THREAD

**Issue by stefa2k** [agebrock/tunnel-ssh#91]
Please support other ssh key formats like ed25519, it gains in popularity recently.

**Comment by agebrock** [comment]
Hi @stefa2k  that's a ssh2 requirement. 
Based on a quick view in the readme i have found 

node.js -- v10.16.0 or newer
node v12.0.0 or newer for Ed25519 key support

**Comment by stefa2k** [comment]
Hi @agebrock thanks for letting me know, I'll take a closer look at the versions!
