### ISSUE TITLE
Untie from ssh2 strict version

### ISSUE THREAD

**Issue by PRR24** [agebrock/tunnel-ssh#93]
If possible, please untie tunnel-ssh from strict ssh2 version and have it more relaxed, so that ssh2 updates can be more easily taken into use. Currently package.json:
```json
"ssh2": "1.4.0"
```
While ssh2 has latest version of 1.8.0

If relaxation is not possible because of some technical reason, please update to depend on latest ssh2.

Thank you.

**Comment by PaulMest** [comment]
My team uses `yarn` so our workaround is to define a [resolution](https://classic.yarnpkg.com/en/docs/selective-version-resolutions/) in `package.json`

```json
{
...
  "resolutions": {
    "ssh2": "1.10.0"
  },
...
}
```

**Comment by Legion2** [comment]
We need ssh2 1.6.0 because of this bug https://github.com/mscdex/ssh2/issues/1127

**Comment by PRR24** [comment]
Legion2, thank you for clarification.
Wondering, if Node 12 (and of course also 10) are EOL at the time of writing, how much is this defect relevant today?
If there are no other constraints, please consider having the dependency as "ssh2": "^1.4.0", In which case, majority (my guess) of users could use latest (1.x) ssh and if somebody still needs to depend on ssh 1.4-1.6, could explicitly install it to satisfy the dependency.
Thanks.

**Comment by agebrock** [comment]
Please try to migrate to version 5. If possible we will update ssh2 regular since its the only dependency from now on .
