### ISSUE TITLE
cpu-features causes build error on M1 macOS

### ISSUE THREAD

**Issue by anselmo-coolstay** [agebrock/tunnel-ssh#95]
tunnel-ssh@4.1.6 uses ssh2@1.4.0 and it uses cpu-features@0.0.2.
But build error is caused when installing it on M1 mac OS.

ssh2@1.11.0 uses cpu-features@0.0.4 and it can be installed without error.

Could you upgrade it, please?

**Comment by agebrock** [comment]
Please try version 5 it uses the latest ssh2 lib
